/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    ModalNovaConta: typeof import('./components/contas/ModalNovaConta.vue')['default']
    ModalNovaServico: typeof import('./components/servico/ModalNovaServico.vue')['default']
    ModalNovoServico: typeof import('./components/servicos/ModalNovoServico.vue')['default']
    ModalUsuariosServico: typeof import('./components/servicos/ModalUsuariosServico.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
