/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/contas/': RouteRecordInfo<'/contas/', '/contas', Record<never, never>, Record<never, never>>,
    '/pedidos/': RouteRecordInfo<'/pedidos/', '/pedidos', Record<never, never>, Record<never, never>>,
    '/servicos/': RouteRecordInfo<'/servicos/', '/servicos', Record<never, never>, Record<never, never>>,
    '/socket/': RouteRecordInfo<'/socket/', '/socket', Record<never, never>, Record<never, never>>,
  }
}
